services:
  atoll:
    build:
      context: .
      dockerfile: Atoll.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - Atoll__DataSource__DataFile=/app/data/packages-meta-ext-v1.json
      - Atoll__DataSource__DataFileUrl=https://aur.archlinux.org/packages-meta-ext-v1.json.gz
      - Atoll__DataSource__RefreshIntervalMinutes=10
      - Atoll__Mongo__ConnectionString=mongodb://admin:change_me@mongo:27017/atoll?authSource=admin
      - Atoll__Mongo__Database=atoll
      - Atoll__Mongo__PackagesCollection=packages
      - Atoll__Mongo__MaxRevisions=10
      - Atoll__Mongo__MaxFileBytes=5242880
      - Atoll__Git__RepositoriesPath=/app/data/repos
    volumes:
      - atoll-data:/app/data
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:8.3.4
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      # https://jira.mongodb.org/browse/SERVER-121912
      - GLIBC_TUNABLES=glibc.pthread.rseq=1
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=change_me
    healthcheck:
      test:
        [ "CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok" ]
      interval: 30s
      retries: 5
      start_period: 15s
      timeout: 5s

volumes:
  atoll-data:
  mongo-data:
